# Generated by Django 4.0.6 on 2022-08-15 23:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Cancion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=25)),
                ('audio', models.CharField(max_length=25)),
                ('imagen', models.CharField(max_length=15)),
                ('duracion', models.IntegerField()),
                ('frecuencia', models.IntegerField()),
                ('idioma', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Sentimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Sentimiento_Cancion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intensidad', models.IntegerField()),
                ('id_cancion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.cancion')),
                ('id_sentimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.sentimiento')),
            ],
        ),
        migrations.CreateModel(
            name='Genero_Cancion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_cancion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.cancion')),
                ('id_genero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.genero')),
            ],
        ),
        migrations.CreateModel(
            name='Artista_Cancion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_artista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.artista')),
                ('id_cancion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.cancion')),
            ],
        ),
    ]
