# Generated by Django 4.0.6 on 2022-08-16 00:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='artista',
            options={'verbose_name': 'artista', 'verbose_name_plural': 'cartistas'},
        ),
        migrations.AlterModelOptions(
            name='artista_cancion',
            options={'verbose_name': 'artista_cancion', 'verbose_name_plural': 'artista_canciones'},
        ),
        migrations.AlterModelOptions(
            name='cancion',
            options={'verbose_name': 'cancion', 'verbose_name_plural': 'canciones'},
        ),
        migrations.AlterModelOptions(
            name='genero',
            options={'verbose_name': 'genero', 'verbose_name_plural': 'generos'},
        ),
        migrations.AlterModelOptions(
            name='genero_cancion',
            options={'verbose_name': 'genero_cancion', 'verbose_name_plural': 'genero_canciones'},
        ),
        migrations.AlterModelOptions(
            name='sentimiento',
            options={'verbose_name': 'sentimiento', 'verbose_name_plural': 'sentimientos'},
        ),
        migrations.AlterModelOptions(
            name='sentimiento_cancion',
            options={'verbose_name': 'sentimiento_cancion', 'verbose_name_plural': 'sentimiento_canciones'},
        ),
        migrations.AlterModelTable(
            name='artista',
            table='artista',
        ),
        migrations.AlterModelTable(
            name='artista_cancion',
            table='artista_cancion',
        ),
        migrations.AlterModelTable(
            name='cancion',
            table='cancion',
        ),
        migrations.AlterModelTable(
            name='genero',
            table='genero',
        ),
        migrations.AlterModelTable(
            name='genero_cancion',
            table='genero_cancion',
        ),
        migrations.AlterModelTable(
            name='sentimiento',
            table='sentimiento',
        ),
        migrations.AlterModelTable(
            name='sentimiento_cancion',
            table='sentimiento_cancion',
        ),
    ]
