# Generated by Django 4.0.6 on 2022-08-16 15:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0002_alter_artista_options_alter_artista_cancion_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_nacimiento', models.DateField()),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'perfil',
                'verbose_name_plural': 'perfiles',
                'db_table': 'perfil',
            },
        ),
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=25)),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.perfil')),
            ],
            options={
                'verbose_name': 'playlist',
                'verbose_name_plural': 'playlists',
                'db_table': 'playlist',
            },
        ),
        migrations.AlterModelOptions(
            name='artista',
            options={'verbose_name': 'artista', 'verbose_name_plural': 'artistas'},
        ),
        migrations.CreateModel(
            name='PlayList_Cancion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_cancion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.cancion')),
                ('id_playlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.playlist')),
            ],
            options={
                'verbose_name': 'playlist_cancion',
                'verbose_name_plural': 'playlist_canciones',
                'db_table': 'playlist_cancion',
            },
        ),
        migrations.CreateModel(
            name='Genero_Triste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_genero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.genero')),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.perfil')),
            ],
            options={
                'verbose_name': 'genero_triste',
                'verbose_name_plural': 'generos_tristes',
                'db_table': 'genero_triste',
            },
        ),
        migrations.CreateModel(
            name='Genero_Feliz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_genero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.genero')),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.perfil')),
            ],
            options={
                'verbose_name': 'genero_feliz',
                'verbose_name_plural': 'generos_felices',
                'db_table': 'genero_feliz',
            },
        ),
        migrations.CreateModel(
            name='Genero_Favorito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_genero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.genero')),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.perfil')),
            ],
            options={
                'verbose_name': 'genero_favorito',
                'verbose_name_plural': 'generos_favoritos',
                'db_table': 'genero_favorito',
            },
        ),
        migrations.CreateModel(
            name='Genero_Enojado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_genero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.genero')),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.perfil')),
            ],
            options={
                'verbose_name': 'genero_enojado',
                'verbose_name_plural': 'generos_enojados',
                'db_table': 'genero_enojado',
            },
        ),
    ]
