# Generated by Django 4.0.6 on 2022-08-16 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_perfil_playlist_alter_artista_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='genero_enojado',
            old_name='id_usuario',
            new_name='id_perfil',
        ),
        migrations.RenameField(
            model_name='genero_favorito',
            old_name='id_usuario',
            new_name='id_perfil',
        ),
        migrations.RenameField(
            model_name='genero_feliz',
            old_name='id_usuario',
            new_name='id_perfil',
        ),
        migrations.RenameField(
            model_name='genero_triste',
            old_name='id_usuario',
            new_name='id_perfil',
        ),
        migrations.RenameField(
            model_name='playlist',
            old_name='id_usuario',
            new_name='id_perfil',
        ),
    ]
