# Generated by Django 4.0.6 on 2022-08-16 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_rename_id_usuario_genero_enojado_id_perfil_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cancion',
            name='audio',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='cancion',
            name='frecuencia',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cancion',
            name='imagen',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
