# Generated by Django 4.0.6 on 2022-09-12 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_cancion_duracion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sentimiento_cancion',
            name='id_cancion',
        ),
        migrations.RemoveField(
            model_name='sentimiento_cancion',
            name='id_sentimiento',
        ),
        migrations.AddField(
            model_name='cancion',
            name='intensidad_enojo',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cancion',
            name='intensidad_feliz',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cancion',
            name='intensidad_triste',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Sentimiento',
        ),
        migrations.DeleteModel(
            name='Sentimiento_Cancion',
        ),
    ]
