# Generated by Django 4.0.6 on 2022-09-13 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_remove_sentimiento_cancion_id_cancion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cancion',
            name='audio',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
