# Generated by Django 4.0.6 on 2022-10-04 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_cancion_audio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cancion',
            name='audio',
            field=models.FileField(upload_to='audios/'),
        ),
        migrations.AlterField(
            model_name='cancion',
            name='duracion',
            field=models.IntegerField(),
        ),
    ]
