# Generated by Django 4.1 on 2022-10-18 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_cancion_audio_alter_cancion_duracion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cancion',
            name='imagen',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
